name: flutter_adaptive_util
description: A comprehensive Flutter package for responsive design with breakpoint management, typography scaling, adaptive spacing, and more.
version: 0.0.1
homepage: https://github.com/Dhia-Bechattaoui/flutter_adaptive_util

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # No assets needed for this package 